### ISSUE TITLE
Pixi installation: How do we control the cuda required?

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-cellpose-sam-task#28]
I'm hitting the following complexity when trying to use Cellpose SAM at the FMI via the pixi installation:
```
2026-04-02 06:31:08,985; cellpose.core; INFO; Neither TORCH CUDA nor MPS version not installed/working.
2026-04-02 06:31:08,985; cellpose.core; INFO; >>>> using CPU
2026-04-02 06:31:08,985; cellpose.core; INFO; >>>> using CPU
base/dir/FRACTAL_TASK_DIR/7/fractal-cellpose-sam-task/0.2.2/source_dir/.pixi/envs/default/lib/python3.14/site-packages/torch/cuda/__init__.py:180: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 12080). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at /pytorch/c10/cuda/CUDAFunctions.cpp:119.)
  return torch._C._cuda_getDeviceCount() > 0
```

Cellpose SAM is unable to use the GPU, because the torch version is:
```
torch.__version__
'2.11.0+cu130'
```

But apparently some (or all?) FMI GPUs only support cuda 12.8, not 13.x.

Given the very limited flexibility we currently have in pixi installation on the Fractal server side (given that it uses the lock file) and the lock specifies:
```
pypi: https://files.pythonhosted.org/packages/47/e8/b98ca2d39b2e0e4730c0ee52537e488e7008025bc77ca89552ff91021f7c/torch-2.11.0-cp314-cp314-manylinux_2_28_x86_64.whl
```

How do we work around this issue? Requiring cuda 13 seems overly strict at the moment (and in general, we can't expect all tasks to always run on systems supporting the newest requirements). 

One workaround I'm trying now is just pip installing the task and pinning torch to 2.10.0

**Comment by tcompa** [comment]
Some first thoughts about this:

We should review https://pixi.prefix.dev/dev/workspace/system_requirements, and notably https://pixi.prefix.dev/dev/workspace/system_requirements/#available-override-options. If setting the env variable `CONDA_OVERRIDE_CUDA="12"` has an effect on `pixi install`, then one way forward could be to run the task collection _without_ using the lockfile, and adding an `export` command to the preamble of the fractal-server/pixi configuration (that is, https://github.com/fractal-analytics-platform/fractal-server/blob/42e081ba7a4a50b704c174078d93e5ea5224fcc8/fractal_server/tasks/config/_pixi.py#L64). This, however, would not provide a solution that works on all nodes, if they have a mix of different cuda versions.

An alternative/complementary option would be to learn about which nodes have cuda 12 vs 13, and then one could edit the SAM task SLURM-runner metadata so that it only runs on some specific nodes (or it does not run on some specific nodes). E.g. if the default lock-based `pixi install` is only compatible with cuda13, one could forbid all nodes that have cuda12.

**Comment by jluethi** [comment]
It looks like the whole FMI cluster has cuda 12.8 as best I can tell, as this occurs in all Cellpose SAM runs I checked. Thus, limiting what we deploy through meta params to won't be the answer. 

We can explore the conda override options.
Alternatively, we could explore having different pixi envs exposed for task installation in the same package rather than just default, e.g. specifically having one with a lock to cuda to 12 and exposing a way for the user to select which pixi env they want to install the task with, e.g. cuda12 or cuda13 (instead of always getting default)

(still working on a test with pip in the meantime)

**Comment by tcompa** [comment]
> Alternatively, we could explore having different pixi env

The original plan with @lorenzocerrone was to only use a given environment for all collections, which is currently encoded in `resource.tasks_pixi_config["DEFAULT_ENVIRONMENT"]`. It is still in principle doable to make this an optional per-collection variable. If that's the best plan, let's move to a `fractal-server` issue and review all details.

**Comment by jluethi** [comment]
Let me first debug whether the pip collection actually works. And then see if I can actually verify the all cuda 12.8 assumption I'm making based on the reviewed job logs

**Comment by jluethi** [comment]
Ok, can now confirm that it works fine with a pip collection, as long as I post-pin:
torch 2.10.0
torchvision 0.25.0

(pre-pinning torch doesn't help and only pinning torch leads to another error, but the 2 combined seem to do the trick)

**Comment by jluethi** [comment]
And according to the cluster wiki, they have CUDA: 11.7, 12.8 => no cuda 13

**Comment by jluethi** [comment]
Given that we have a workaround with the pip installation, let's carefully review how we want to handle this. Because I think we'll hit similar issues in the future and should think more broadly about the needed pixi flexibility for things like varying CUDA availability or other similar topics.

**Comment by lorenzocerrone** [comment]
I think that making CUDA an explicit system dependency might fix it, since pixi has access to the CUDA drivers installed on the machine through pixi info. Before continuing the discussion, I would like to try setting up a couple of example pixi.toml. @jluethi it would be great if we could do some live testing together since you have access to the FMI cluster :)

**Comment by jluethi** [comment]
Yes, let's do some live testing with some options when you're back @lorenzocerrone and we can evaluate the needs for pixi configurability based on that :)

One note for that:

> I think that making CUDA an explicit system dependency might fix it

my understanding is that we can't provide CUDA through pixi. Pixi may see what CUDA is available. Whether pixi can then pick the right torch whl based on knowing the CUDA available is a good question though!
